### ISSUE TITLE
Phaser append url problem

### ISSUE THREAD

**Issue by Dchau95** [niculistana/Liars-Dice#15]
When trying to load assets from phaser, it appends the url one back slash instead of appending to the root directory.

**Comment by Dchau95** [comment]
Fixed the phaser append error. It was because phaser thought base url was localhost:3000/games. Base url changes according to where the javascript file is loaded, for example if the game.js file is loaded in pages/index, Phaser will assume the images are located at the root of the server. On the other hand, since game.js was also loaded from games/show.html.erb, it thought the base url was localhost:3000/games. Phaser allows us to change the base url, so I did that. Just need to remember to change the base url when uploading the project to heroku.

**Comment by niculistana** [comment]
Good job man, cheers! - nicu
