### ISSUE TITLE
Error upon checking out `user-auth` branch

### ISSUE THREAD

**Issue by niculistana** [niculistana/Liars-Dice#4]
Small snippet of the error:

/Users/niculistana/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in `const_get': uninitialized constant User (NameError)
    from /Users/niculistana/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in`block in constantize'
    from /Users/niculistana/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `each'
    from /Users/niculistana/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in`inject'
    from /Users/niculistana/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `constantize'
    from /Users/niculistana/.rvm/gems/ruby-2.2.2/gems/devise-3.5.6/lib/devise.rb:292:in`get'
    from /Users/niculistana/.rvm/gems/ruby-2.2.2/gems/devise-3.5.6/lib/devise/mapping.rb:81:in `to'
    from /Users/niculistana/.rvm/gems/ruby-2.2.2/gems/devise-3.5.6/lib/devise/mapping.rb:76:in`modules'

**Comment by niculistana** [comment]
@Majiccow Any tips on how you got your branch working?

**Comment by JoshuaAJohansen** [comment]
Hey Nicu. Are you still having this issue? I don't think the db was migrated correctly. 

Pulling most recent user-auth should work.

**Comment by niculistana** [comment]
@Majiccow Just pulled your branch. It now works. I am closing this issue.

**Comment by JoshuaAJohansen** [comment]
Awesome, Glad to hear it.
