### ISSUE TITLE
Diepool not removing die properly

### ISSUE THREAD

**Issue by niculistana** [niculistana/Liars-Dice#7]
Under the spritegroup branch: https://github.com/niculistana/CSC667WebApp/tree/spritegroup

For some reason when I call removeDie(3) and render the sprites using one of the test buttons, the die does not get removed.

I tried printing on the console to see how many items are in the array, and it does decrease. If anybody could help that would be great!

**Comment by Dchau95** [comment]
Checking out the problem now. Still don't know what exactly causes this issue, but a side effect I noticed is that whenever you remove a dice and then re-render, a dice with the number 1 replaces the bottom sprites from right to left. 

EDIT: Whenever you remove a die, it'll replace the replaced die with the die that appeared on the bottom most, right die. 

EDIT: Found out that there was a remove function for groups, so I implemented that. The remove function needs to know the last sprite. Also, I changed from removing from the fourth element to the last element. So it manages to re-render the dice with the last element removed. But only once, no wonder why it only works once.
